### ISSUE TITLE
Generic dissector did NOT succeed

### ISSUE THREAD

**Issue by R00iBaard** [Johann-Angeli/wireshark-plugin-mqtt#1]
Hi there, I get this error when re load Wireshark with the files placed in the relevant plugins directory. See screenshot if it helps.

<img width="255" alt="screen shot 2016-11-01 at 4 45 08 pm" src="https://cloud.githubusercontent.com/assets/11412240/19893659/97c04b22-a052-11e6-8721-d4256566596b.png">

**Comment by Johann-Angeli** [comment]
Hi,

MQTT and MQTT/SN are now supported by latest versions of Wireshark.
The error message seems to be related to that (a protocol named MQTT is already defined).

Try to remove my protocol from your installation. It seems my plugin is no more needed :/ .
